FROM ubuntu:22.04

# installing linux packages
RUN apt-get update && apt-get upgrade
RUN apt-get install -y nmap net-tools iputils-ping python3 python3-pip sudo passwd openssl dnsutils nano curl openjdk-8-jdk

RUN mkdir /jarfiles && curl -L -o /jarfiles/ojdbc8.jar https://download.oracle.com/otn-pub/otn_software/jdbc/235/ojdbc8.jar

# installing python packages
RUN pip3 install oracledb pyspark

ENTRYPOINT [ "tail", "-f", "/dev/null" ]