FROM ubuntu:22.04

# installing linux packages
RUN apt-get update && apt-get upgrade
RUN apt-get install -y nmap net-tools iputils-ping python3 python3-pip sudo passwd openssl dnsutils nano

# installing python packages
RUN pip3 install oracledb

ENTRYPOINT [ "tail", "-f", "/dev/null" ]