FROM ubuntu:22.04

SHELL ["/bin/bash", "-c"]

#installing linux packages
RUN apt-get update && apt-get upgrade
RUN apt-get update && apt-get install -y nmap net-tools iputils-ping sudo passwd openssl dnsutils nano curl openjdk-8-jdk
